### ISSUE TITLE
SSO Issue with Office 365

### ISSUE THREAD

**Issue by fr500** [haiwen/seafile-client#1258]
https://forum.seafile.com/t/problems-with-sso-and-office-365/10801/2

I’m having an issue with the desktop client and SSO.
When I login thru a web browser with SSO I am redirected to this page:

![image](https://user-images.githubusercontent.com/1721040/71927262-1b6ef000-3163-11ea-8ba9-ec07d482b601.png)

But when I login via the client, I enter my seafile server URL and then what I get is this:

![image](https://user-images.githubusercontent.com/1721040/71927294-2aee3900-3163-11ea-9a69-1bff85da9711.png)

The view doesn’t render properly and as a result users can’t login.
I copied the URL to a browser (another one just to test) and it worked fine, so it’s something with the web view.

How can we address this?

**Comment by fr500** [comment]
Update: it works fine on android:

![image](https://user-images.githubusercontent.com/1721040/71927373-52450600-3163-11ea-8125-13fe9d2603e5.png)

**Comment by fr500** [comment]
@killing sorry to bother you, do you think this can be worked around? or should I switch to local users?

**Comment by freeplant** [comment]
I suggest you to switch to local users.

**Comment by fr500** [comment]
Gee that sucks honestly.
https://seafile.gitbook.io/seafile-server-manual/deploying-seafile-under-linux/oauth-authentication

The implementation works fine in the web client and seadroid.
There should be a way to fix this.

**Comment by fr500** [comment]
This is so discouraging...

**Comment by HolySephi** [comment]
Yeah we are having the same issue. Looks like the internal browser of the client (and seadrive-client) does not react to the redirection to the actual login-page.

**Comment by HolySephi** [comment]
fixed in client version 8 (currently beta)

**Comment by NicolaiSchmid** [comment]
A similar issue persists, Webauthn is still not supported. 

The client shouldn't try and host its own browser. It should forward to the OS default browser and then set the redirect URI to a localhost server where the client is listening for the response. That way, the client doesn't have to maintain all the standards current browsers support for authentication and JavaScript.

**Comment by killing** [comment]
@NicolaiSchmid Thank you for your suggestion. We'll consider about it.
