### ISSUE TITLE
Error when indexing in 9.0.5, all fine with 9.0.4

### ISSUE THREAD

**Issue by dionysius** [haiwen/seafile-client#1521]
I have issues with a specific library sync since 9.0.5. The library is set to sync with `C:\Users\Dionysius\Documents`. **I have no issues with 9.0.4**. Upgrading back to 9.0.5 and the error repeats again. I also tried to completely unsync this library and set it up again, same issue.

systeminfo:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Dionysius
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 97 Stepping 2 AuthenticAMD ~4701 Mhz
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Total Physical Memory:     31’893 MB
```

UI -> Library overview:
![screenshot 437](https://github.com/haiwen/seafile-client/assets/1341084/3c944bff-5ee3-4849-b4de-1d7e14cc0180)

UI -> Show errors:
![screenshot 436](https://github.com/haiwen/seafile-client/assets/1341084/3e768845-d9d3-4b81-93f0-a7a612a21b7e)

seafile.log
```
[03/09/24 10:26:49] Repo 'pc-documents' sync state transition from 'synchronized' to 'committing'.
[03/09/24 10:26:50] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Music: 5.
[03/09/24 10:26:50] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Pictures: 5.
[03/09/24 10:26:50] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Videos: 5.
[03/09/24 10:26:50] Repo 'pc-documents' sync is finished but with error: Error when indexing
[03/09/24 10:26:50] Repo 'pc-documents' sync state transition from 'committing' to 'initializing'.
[03/09/24 10:26:50] Repo 'pc-documents' sync is finished but with error: Error when indexing
```

events.log and applet.log doesn't contain anything useful.

---

What is weird is `My Videos`, `My Pictures` and `My Music` are not part of `Documents`. I only sync `Pictures` set to `C:\Users\Dionysius\Pictures` and shows no issues (it even uploaded the screenshots created above since they are created inside there). So to be clear, I am not syncing `Videos` and `Music` - they contain stuff but I don't need them synced.

**Comment by feiniks** [comment]
Hello @dionysius, this is a known issue. We will fix it in the next release.

**Comment by killing** [comment]
This is fixed in 9.0.6.

**Comment by dionysius** [comment]
Unfortunately 9.0.6 did not solve this issue entirely. It's somewhat weird. Maybe there are two issues here.

Seafile Desktop Client cleanly closed. Open it freshly:

```
[05/24/24 07:50:45] starting seafile client 9.0.6
[05/24/24 07:50:45] client id = d9fd18d9aece1965d2cda3dd104fd94b4985dedb, client_name = pc-dionysius
[05/24/24 07:50:45] Commit a67fa42f7f51d18786478263352c4b817b664185 is missing
[05/24/24 07:50:45] rpc server started.
[05/24/24 07:50:45] Removing store C:\Users\Dionysius\scoop\persist\seafile-syncing-client\data\deleted_store\fs\ba8daac3-3fcd-4505-9104-ce61aeb05680
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] File syncing protocol version on server https://cloud.XXXXXX.XX is 2. Client file syncing protocol version is 2. Use version 2.
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:46] start to serve on pipe client
[05/24/24 07:50:47] Repo 'pc-pictures' sync state transition from 'synchronized' to 'committing'.
[05/24/24 07:50:50] All events are processed for repo 9651aaa6-e269-4ca7-81b2-04f5ab62cc98.
[05/24/24 07:50:50] Repo 'pc-pictures' sync state transition from 'committing' to 'initializing'.
[05/24/24 07:50:51] Repo 'pc-desktop' sync state transition from 'synchronized' to 'committing'.
[05/24/24 07:50:51] All events are processed for repo 31579d33-e0d8-40e4-82ed-3f5652f2dc4f.
[05/24/24 07:50:51] Repo 'pc-desktop' sync state transition from 'committing' to 'initializing'.
[05/24/24 07:50:52] Repo 'pc-documents' sync state transition from 'synchronized' to 'committing'.
[05/24/24 07:50:52] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Music: 5.
[05/24/24 07:50:52] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Pictures: 5.
[05/24/24 07:50:52] FindFirstFile failed \\?\C:\Users\Dionysius\Documents\My Videos: 5.
[05/24/24 07:50:53] All events are processed for repo ba8daac3-3fcd-4505-9104-ce61aeb05680.
[05/24/24 07:50:53] Repo 'pc-documents' sync is finished but with error: Error when indexing
[05/24/24 07:50:53] Repo 'pc-documents' sync state transition from 'committing' to 'initializing'.
[05/24/24 07:50:53] Repo 'pc-documents' sync is finished but with error: Error when indexing
[05/24/24 07:50:54] Repo 'pc-saved-games' sync state transition from 'synchronized' to 'committing'.
[05/24/24 07:50:54] All events are processed for repo 5e26cde1-6a7e-426d-82fe-4d0f0d21f0a2.
[05/24/24 07:50:54] Repo 'pc-saved-games' sync state transition from 'committing' to 'initializing'.
```

![image](https://github.com/haiwen/seafile-client/assets/1341084/c8fc009c-f6b3-48e4-bddd-8acb38779ecd)

After opening file sync errors ...

![image](https://github.com/haiwen/seafile-client/assets/1341084/5e7ffd46-3a74-4e90-b72b-1ec49125c002)

... and going back to the UI:
![image](https://github.com/haiwen/seafile-client/assets/1341084/3e2b557b-c347-4ed4-bc84-1a609b18da8e)

For the rest of the time the library stays healthy, unless I restart seafile client again (or the pc).

**Comment by jacob-pro** [comment]
Hello I am seeing the same issue in 9.0.6

```
[06/12/24 23:15:42] Repo 'Documents' sync state transition from 'synchronized' to 'committing'.
[06/12/24 23:15:44] FindFirstFile failed \\?\C:\Users\jacob\Documents\My Music: 5.
[06/12/24 23:15:44] FindFirstFile failed \\?\C:\Users\jacob\Documents\My Pictures: 5.
[06/12/24 23:15:44] FindFirstFile failed \\?\C:\Users\jacob\Documents\My Videos: 5.
[06/12/24 23:15:44] All events are processed for repo 322e05b2-2a35-42ca-9279-6b8a77009993.
[06/12/24 23:15:44] Repo 'Documents' sync is finished but with error: Error when indexing
[06/12/24 23:15:44] Repo 'Documents' sync state transition from 'committing' to 'initializing'.
[06/12/24 23:15:44] Repo 'Documents' sync is finished but with error: Error when indexing
```

**Comment by dionysius** [comment]
Kindly asking to reopen this issue @killing @feiniks. We believe this issue is not fixed yet.

**Comment by nicksukie** [comment]
I'm having this issue in 9.0.8
