### ISSUE TITLE
Failed to create dir

### ISSUE THREAD

**Issue by NNois** [haiwen/seafile-client#464]
i've updated to 4.0 and i can't sync anymore any library
look at the wrong slashes order !? (we are on windows shares)

[02/16/15 18:27:37] transfer-mgr.c(310): Transfer repo '41e3d74a': ('normal', 'get-chunk-server') --> ('normal', 'data')
[02/16/15 18:27:37] vc-utils.c(567): Failed to create dir \\Mdpsrv-gre2\jobs\15\1501_RTS_MISCI\1501_RTS_MISCI_IO/WIP.

**Comment by killing** [comment]
What's the local path of your library? It's not the problem of slashes. Before doing any I/O operation, the slashes will be converted to '\'. The problem should be your local path string.

**Comment by NNois** [comment]
it's not this library specific but all my libraries sitting on the local network.
For example this one is \\Mdpsrv-gre2\jobs\15\1501_RTS_MISCI\1501_RTS_MISCI_IO

this used to work before... solved for now partialy by using a network drive but i would prefer a toon not using them...

**Comment by killing** [comment]
In the new version, we add prefix "\\?\" for every path to handle paths longer than 260 characters. According to https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath, network share paths ("\\share\...") cannot be handled. To handle it we must use "\\?\UNC\" prefix. Network share doesn't work very well with Seafile client anyway. Sometimes file change detection is not working. We'll try to solve these two problem together.

**Comment by smarsching** [comment]
I think that I am experiencing the same problem. I have the Seafile folder in the "Documents" folder which is redirected to a network share by a group policy. Up to Seafile Client 4.0.6, everything worked fine. With Seafile Client 4.0.7 the libraries do not sync any longer, reporting an "Error when accessing the local folder". Using a mapped network drive instead of a UNC path seems to fix the problem though.

For the moment, I have downgraded back to 4.0.6, which fixed the problem for me, but it would be nice if this could be fixed in a future version.

PS: The file change detection does not work for me either, but this problem obviously is less severe, because I can always trigger a sync manually. However, it would be nice if this bug would eventually be fixed, too.

**Comment by bbbenjie** [comment]
Hey guys, will there be a fix for this bug in the upcoming minor versions?
I have the same environment as @smarsching (folder redirection via GPO) and this bug prevents me from updating my seafile clients to 4.0.7 and newer.

**Comment by killing** [comment]
It'll be fixed in 4.2 release cycle. Now you can map the share as network
drive.

2015-04-25 19:15 GMT+08:00 bbbenjie <notifications@github.com>:

**Comment by smarsching** [comment]
This problem is not fixed for me in version 4.2.0 of the Windows client.

If the path to the `seafile-data` directory specified in `seafile.ini` is a UNC path, I get the following error message when trying to synchronize a library that has not been synchronized before:

> index file open failed
> Failed to load index file.

Then, there are a few non-error messages from `http-tx-mgr.c` and the error messages are repeated. In the GUI, the repository remains in the "downloading" state forever.

When the path to the `seafile-data` directory is not a UNC path but the path to the repository is a UNC path, I get the following error messages:

> vc-utils.c(567): Failed to create dir //server/share/path/to/repository/folder-in-repository.

This message is repeated many times. After that, there are more error messages:

> http-tx-mgr.c(674): Transfer repo '&lt;repository ID&gt;': ('normal', 'data') --> ('finished', 'finished')
> http-tx-mgr.c(1115): Parse response failed: '[' or '{' expected near 'If'.
> wt-monitor-win32.c(565): GetQueuedCompletionStatus failed, error code 87
> clone-mgr.c(803): Transition clone state for &lt;repository ID&gt; from [fetch] to [done].
> repo-mgr.c(578): Failed to stat worktree //server/share/path/to/repository for repo '&lt;repository name&gt;'(&lt;repository ID&gt;)

The last message is again repeated many times.

**Comment by killing** [comment]
Sorry for the delay. We were too busy at adding icon overlay support to the
4.2.0 version. This will be fixed in one or two tiny releases.

2015-05-14 4:18 GMT+08:00 Sebastian Marsching <notifications@github.com>:

**Comment by killing** [comment]
I've fixed it in the code. It'll be available in 4.2.2.

**Comment by bbbenjie** [comment]
Thanks for the great news. I can confirm it is fixed in the current version 4.2.2.

**Comment by smarsching** [comment]
I can also confirm that the problem is fixed for me in version 4.2.3 and synchronization with UNC paths works again. Thank you very much for the bugfix.

Change detection, however, still does not seem to work for UNC paths (synchronization has to be triggered manually).

**Comment by shoeper** [comment]
Network shares do not (technically) support change detection.
They have to be synced manually.

**Comment by smarsching** [comment]
I am not an expert in Windows system programming, so I do not know through which API this functionality is exposed, but the SMB protocol seems to support change notifications:
https://msdn.microsoft.com/en-us/library/jj216044.aspx

**Comment by Napsty** [comment]
It seems I hit the same bug, but with the currently latest Seafile client 4.4.2 on Windows 7. Client logs show:

	[10/27/15 14:43:40] clone-mgr.c(812): Transition clone state for 7070005f from [init] to [connect].
	[10/27/15 14:43:40] clone-mgr.c(812): Transition clone state for 7070005f from [connect] to [fetch].
	[10/27/15 14:43:40] http-tx-mgr.c(3930): Download with HTTP sync protocol version 1.
	[10/27/15 14:43:40] http-tx-mgr.c(959): Transfer repo '7070005f': ('normal', 'init') --> ('normal', 'check')
	[10/27/15 14:43:40] http-tx-mgr.c(959): Transfer repo '7070005f': ('normal', 'check') --> ('normal', 'commit')
	[10/27/15 14:43:40] http-tx-mgr.c(959): Transfer repo '7070005f': ('normal', 'commit') --> ('normal', 'fs')
	[10/27/15 14:43:40] http-tx-mgr.c(959): Transfer repo '7070005f': ('normal', 'fs') --> ('normal', 'data')
	[10/27/15 14:43:41] http-tx-mgr.c(959): Transfer repo '7070005f': ('normal', 'data') --> ('finished', 'finished')
	[10/27/15 14:43:41] http-tx-mgr.c(1555): Bad response code for GET https://seafile.example.com/seafhttp/repo/folder-perm: 404.
	[10/27/15 14:43:41] clone-mgr.c(812): Transition clone state for 7070005f from [fetch] to [done].
	[10/27/15 14:43:42] sync-mgr.c(660): Repo 'My Library' sync state transition from 'synchronized' to 'committing'.
	[10/27/15 14:43:42] repo-mgr.c(3125): All events are processed for repo 7070005f-36ae-448c-9923-a3874d6e79c8.
	[10/27/15 14:43:42] sync-mgr.c(660): Repo 'My Library' sync state transition from 'committing' to 'initializing'.
	[10/27/15 14:43:42] http-tx-mgr.c(1555): Bad response code for GET https://seafile.example.com/seafhttp/repo/folder-perm: 404.
	[10/27/15 14:43:42] http-tx-mgr.c(1833): Bad response code for GET https://seafile.example.com/seafhttp/repo/locked-files: 404.
	[10/27/15 14:43:42] sync-mgr.c(1479): Removing blocks for repo My Library(7070005f).
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.
	[10/27/15 14:44:52] vc-utils.c(567): Failed to create dir C:/Users/kuenzlerc/Seafile\Documents/Projects | Clients.

From then on the sync is stuck at 1% and does not continue.

The library used to work to download in the past. I cannot tell from which client version on it stopped working.

**Comment by Napsty** [comment]
Nevermind - the mentioned folder name had a pipe (|) in it and Windows refuses this character.
