### ISSUE TITLE
Can't sync 

### ISSUE THREAD

**Issue by Lordroran** [haiwen/seafile-client#563]
From seacloud.cc:
Client Version 4.2.0
Can't sync with servers without configured behind Nginx/Apache but listen on port 80, showing "Waiting for synchronization".

**Comment by shoeper** [comment]
https://seacloud.cc/group/3/wiki/client-changelog/

And what's the problem if the issue is already known?

**Comment by freeplant** [comment]
Just a small issue, will be fixed soon.

**Comment by Lordroran** [comment]
Not better in 4.2.1

**Comment by killing** [comment]
What's your server version? Client 4.2.1 only supports servers 4.0+.
If you already use 4.0+ server, please post your seafile.log here.

2015-05-16 4:00 GMT+08:00 Lordroran <notifications@github.com>:

**Comment by K-os** [comment]
This bug also affects me and still persists in Seafile Client 4.2.1 (both Windows 7 and Linux).

Windows seafile.log contains this:

    [05/17/15 00:23:13] seaf-daemon.c(504): starting seafile client 4.2.1
    [05/17/15 00:23:13] seaf-daemon.c(506): seafile source code version 190876f1970ef493081eb38dac8d30f5d3b6fa30
    [05/17/15 00:23:13] ../common/mq-mgr.c(60): [mq client] mq cilent is started
    [05/17/15 00:23:13] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seafile.heartbeat
    [05/17/15 00:23:14] http-tx-mgr.c(405): libcurl failed to GET https://${my_server}/seafhttp/protocol-version: SSL connect error.

Linux seafile.log:

    [05/16/15 23:40:23] seaf-daemon.c(504): starting seafile client 4.2.1
    [05/16/15 23:40:23] ../common/mq-mgr.c(60): [mq client] mq cilent is started
    [05/16/15 23:40:23] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seafile.heartbeat
    [05/16/15 23:40:25] http-tx-mgr.c(405): libcurl failed to GET https://${my_server}/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.



The server is running seafile-server-4.1.2 on Linux behind Nginx.
Nginx has the following SSL-configuration:

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA';


This configuration works perfectly with client v4.1.6

**Comment by shoeper** [comment]
You have to setup http(s) sync. 4.2.x removed syncing over port 10001 and 12001.

**Comment by killing** [comment]
4.2 client removes support for non http sync. You have to add your custom
CA to the system repository if you are using self-sign certificate, or
"disable verify certificate" in client settings.

2015-05-17 7:34 GMT+08:00 Gabriel <notifications@github.com>:

**Comment by K-os** [comment]
Http(s)-Syncing ja enabled in the client. Do I have to change anything on the server?
The server certificate is singed by CaCert and the root is installed on the client machines (this used to work).

Interestingly, on the Windows-machine a popup came up and said the RSA-key changed, but the hash shown did not belong to the certificate used by Nginx. The pop-up was not very helpful: it only showed the new and the old hash. Neither did it print the hash function used, nor did it print the subject-alt-name or CN of the certificate.

Is it possible that SNI (server name indication) is not working correctly in the client so it gets presented the wrong certificate by the server?

**Comment by killing** [comment]
No the code for handling http(s) connection has not been changed. The linux
client uses openssl and usually doesn't have https connection problems. If
it doesn't work on Linux, it's usually a server https configuration problem.
Have you tried to connect to seacloud.cc, our official server? I tested
with the latest client and it has no problem connecting to it.

2015-05-17 15:23 GMT+08:00 Gabriel <notifications@github.com>:

**Comment by MrEasy** [comment]
Same problem here with Apache and HTTPS with self-signed certificate, which was chosen to be accepted when configuring seafile-client.
Seafile client: 4.2.2
Seafile server: 4.1.2

Syncing libraries that were once downloaded to client works flawlessly.
Syncing new libraries fails.

client log gives repeated:
```
[05/27/15 10:51:04] http-tx-mgr.c(538): libcurl failed to GET https://server:443/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.
[05/27/15 10:51:04] clone-mgr.c(812): Transition clone state for 2fd52684 from [connect] to [connect].
[05/27/15 10:51:09] clone-mgr.c(812): Transition clone state for 2fd52684 from [connect] to [connect].
```

**Comment by K-os** [comment]
Ok, the Windows client version 4.2.2 fixed the problem for me.
On the linux side the problem was, that the root certificate was not installed properly. Manually accepting the certificate in the client didn't help, so that seems to be still broken.

**Comment by killing** [comment]
Have a try 4.2.3 client, just updated. Manually accepting the certificate
should work now.

2015-05-29 19:34 GMT+08:00 Gabriel <notifications@github.com>:

**Comment by MrEasy** [comment]
@killing 4.2.3 client works fine now - thanks.

**Comment by mandano** [comment]
Hi,

i installed the new client on mac 4.2.3, and i have still the same issue. Before i switched to the 443 port sync only it fine. Server version is the current linux one. Any suggestion? what i could do, respectivley what information do you need more to debug.


http-tx-mgr.c(639): libcurl failed to GET https://url/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.

best regards

jan

**Comment by killing** [comment]
Please try the methods in "Client Side Configuration for HTTPS" of this manual page: http://manual.seafile.com/deploy/deploy_http_sync.html

**Comment by mandano** [comment]
Hi thanks for your reply. 
It only works when i check "Do not verifiy server certificate in HTTPS sync". I followed the certificate generation instruction on the server  for a self-signed certificate. As i renewed my certificate the pop up came up to confirm the certificate but the error still came up.

**Comment by MrEasy** [comment]
@mandano @killing @freeplant  worth to mention, that my comment above also holds true only with explicitely set "Do not verifiy server certificate in HTTPS sync"

**Comment by Chilledheart** [comment]
@mandano If you are using a mac client, you can simply drag your custom CA certificate into login Keychain in `Keychain Access` and set it as trusted. This should solve your problem. This support is added in 4.2.2.

**Comment by mandano** [comment]
i did drag my certificate into the keychain management app. Sadly its still the same issue.

**Comment by Chilledheart** [comment]
@mandano you also need to set your root certificate to `Always Trust` (at least for `Secure Sockets Layer`).

**Comment by mandano** [comment]
Thank you very much!! thats it. Now it works. Thanks for your fast responses.

**Comment by mandano** [comment]
i am getting this error again, although 2 of 3 libraries are synced. 1 cant be synced and waits for synchronising.

**Comment by mandano** [comment]
hi again,

i have the strange issue, that half of my libraries can sync the other not. Also i m still getting the error 
[06/04/15 20:11:07] http-tx-mgr.c(639): libcurl failed to GET https://.../seafhttp/protocol-version: Couldn't connect to server.
My certificate is trusted in in my keychain manager. If i check "dont check for certificate" nothing changes. What can i do from here? What could i debug?

Thx.

**Comment by Chilledheart** [comment]
@mandano can you try with unsync and then sync your broken libraries?

**Comment by killing** [comment]
If some of your libraries are created before 3.0 version, you have to keep
the port 10001 and 12001 open on the server.
The "couldn't connect to server" error should only show up after the
computer starts, when no network connection is available. That actually
means the connect() system call fails. It has nothing to do with
certificate.

2015-06-05 2:14 GMT+08:00 mandano <notifications@github.com>:

**Comment by kopax** [comment]
I have the same issue, I don't wan't to upgrade the server because last upgrade to 4.x was buggy.
How can I download seafile client 3.1.11?
I will try the 4.x server with 4.x client on a test environment when I will have time, until then, I can't provide the client to my user.

**Comment by mandano** [comment]
hi again, today i could try what you said chilledheard respectively killing , to resync the libraries and: it now works flawless!!! THX. Although i have to say from my amateur point of view, the protocol messages were misleading.

**Comment by shoeper** [comment]
@kopax https://bitbucket.org/haiwen/seafile/downloads/
But I did not find any bugs in 4.x so far.
