### ISSUE TITLE
Windows Explorer crashes

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#628]
Windows Explorer crashes repeatedly
Event log says:
```
Name der fehlerhaften Anwendung: explorer.exe, Version: 6.1.7601.17567, Zeitstempel: 0x4d672ee4
Name des fehlerhaften Moduls: seafile_shell_ext64.dll, Version: 0.0.0.0, Zeitstempel: 0x55790e16
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000059eab 
```

English translation:
```
Application: explorer.exe, Version: 6.1.7601.17567, Timestamp: 0x4d672ee4
Faulty module: seafile_shell_ext64.dll, Version: 0.0.0.0, Timestamp: 0x55790e16
Exception code: 0xc0000005
Error offset: 0x0000000000059eab 
```

Client Version 4.2.4

**Comment by lins05** [comment]
Thanks for reporting. We are looking into this and would fix it asap.

**Comment by liayn** [comment]
Just some more info, maybe that is relevant.

I've a more explorer extensions running:
* TortoiseGit
* Dropbox
* Seafile

Maybe the crash is related to those not playing together smoothly.

**Comment by shoeper** [comment]
I can verify this. On my windows 8.1 machine(s) I do also have issues with the explorer extension.

 1. Somtimes the explorer restarts often.
 2. Often the rightclick menu is extremely slow
 3. A not so important issue is also that the right click menu looks not native anymore.

**Comment by liayn** [comment]
Win7 64bit

1.) ACK
2.) can't confirm
3.) ACK

**Comment by freeplant** [comment]
Can you try v4.2.5? It fixes one place that may cause the problem. There may be other places.

**Comment by freeplant** [comment]
We have released v4.2.6, containing more fixes on this issue.

**Comment by liayn** [comment]
Will update now. lets see ;-)

**Comment by shoeper** [comment]
Explorer still crashes frequently, when seafile explorer extension is enabled.

**Comment by liayn** [comment]
Just had a explorer crash after back up from sleep mode.

```
Name der fehlerhaften Anwendung: Explorer.EXE, Version: 6.1.7601.17567, Zeitstempel: 0x4d672ee4
Name des fehlerhaften Moduls: ntdll.dll, Version: 6.1.7601.18869, Zeitstempel: 0x556366f2
Ausnahmecode: 0xc0000374
Fehleroffset: 0x00000000000bfc22
ID des fehlerhaften Prozesses: 0x13e0
Startzeit der fehlerhaften Anwendung: 0x01d0aece4ecf098b
Pfad der fehlerhaften Anwendung: C:\Windows\Explorer.EXE
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: 0dd37425-1b75-11e5-9863-809504ac6031
```

**Comment by killing** [comment]
@liayn @shoeper Seems the easiest way to debug this problem is to use a JIT debugger. It catches the exception when explorer crashes.

Can you install Dr.MinGW? https://github.com/jrfonseca/drmingw

And this debug package contains debug symbols for the explorer extension: https://seacloud.cc/f/afb35a75ca/

After installing these, when explorer crashes again, you should choose "Debug" in the pop-up dialog. Then Dr.MinGW will kick in. But this tool is somehow slow. Since explorer is large, it takes 1-2 minutes to print the back trace. So be patient...

Thanks for helping.

**Comment by liayn** [comment]
Installed that. lets see

**Comment by liayn** [comment]
status report: no crash until now.

**Comment by shoeper** [comment]
I cannot install the provided Seafile Client (I think because windows thinks it is already installed, based on e.g. version number). 
Will my accounts stay on my computer when uninstall it an install the debug client?

**Comment by liayn** [comment]
It asks you whether they should stay on uninstall

**Comment by shoeper** [comment]
Ok thanks. It worked.

**Comment by shoeper** [comment]
Just had another crash but there was not popup  ore something similiar I could use to get debugging information.

**Comment by killing** [comment]
@shoeper Have you installed dr.MinGW? What OS do you use?

**Comment by shoeper** [comment]
I've installed it using `drmingw -i` as admin in the bin folder and got a "successfull" message.
I'm using Windows 8.1 Pro. I can try a restart of my device later.

**Comment by killing** [comment]
@shoeper It seems related to Windows 8+. You have to disable "Problem Reporting" in the system.
I found a discussion here: http://comments.gmane.org/gmane.comp.gnu.mingw.user/41044
And the way to disable it: http://blog.laptopmag.com/disable-error-reporting-windows

**Comment by shoeper** [comment]
Ok. I did that. No crash so far, but Seafile uses 80% CPU permanently.

![](https://mno.pw/0832)

**Comment by shoeper** [comment]
When high cpu load occurs I get these lines in ccnet.log
```
[07/02/15 10:54:48] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)
[07/02/15 10:54:48] ../common/peer.c(943): Local peer down
[07/02/15 10:54:48] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)
[07/02/15 10:54:48] ../common/peer.c(943): Local peer down
[07/02/15 10:54:48] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)
[07/02/15 10:54:48] ../common/peer.c(943): Local peer down
```

and applet.log
```
[07/02/15 10:54:49]failed to get file status for /memcached_stats.sh
[07/02/15 10:54:49][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:49]failed to get path status: Transport Error

[07/02/15 10:54:49]failed to get file status for /memcached_stats.sh
[07/02/15 10:54:49][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:49]failed to get path status: Transport Error

[07/02/15 10:54:49]failed to get file status for /viral-2h.swf
[07/02/15 10:54:49][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:49]failed to get path status: Transport Error

[07/02/15 10:54:49]failed to get file status for /viral-2h.swf
[07/02/15 10:54:49][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:49]failed to get path status: Transport Error

[07/02/15 10:54:49]failed to get file status for /viral-2h.swf
[07/02/15 10:54:49][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:49]failed to get path status: Transport Error

[07/02/15 10:54:49]failed to get file status for /viral-2h.swf
[07/02/15 10:54:50][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:51][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:52][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:53][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:54][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:55][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:56][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:57][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:58][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:54:59][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:00][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:01][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:02][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:03][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:04][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:05][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:06][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:07][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:08][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:09][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:10][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:11][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:12][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:13][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:14][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:15][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:16][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:17][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:18][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:19][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:20][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:21][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:22][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:23]failed to read request from shell extension: Die Pipe wurde beendet.

[07/02/15 10:55:23]An extension client is disconnected: GLE=109

[07/02/15 10:55:23][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:24][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:25][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:26][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:27][Sea RPC] Bad response: 102 processor is dead.
[07/02/15 10:55:27]failed to get repo list: Transport Error
```
and no new entries in seafile.log

**Comment by liayn** [comment]
@killing that applies to Win7 as well obviously. I had 2 crashes today, but DrMinGw never showed up. I disabled problem reporting now.

**Comment by Chilledheart** [comment]
Hi all,
Here is a HOWTO to get gdb to work in your computer:

1. Grab msys2 installer from http://msys2.github.io/ (choose x86_64 version please)
2. Open Start Menu -> All Programs -> MSYS2 64bit -> MinGW-w64 Win64 Shell
3. Execute `pacman -Sy mingw-w64-x86_64-gdb` in the MINGW64 shell
4. Get the PID of your current `explorer.exe` process, e.g. `3944`
5. Execute `gdb -p 3944` (replace `3944` with the PID the previous step)
6. When gdb successfully attachs the target process, type `c` and press Enter to
   continue the execution of that process.
7. Return back to work
8. When explorer.exe crashes, you will get a stop in the gdb terminal. type `bt` and press
   Enter there to view the backtrace which you might want to report to us.

**Comment by liayn** [comment]
drmingw now has something to say:

```
CREATE_PROCESS PID=4860 TID=4864 explorer.exe
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000076D30000 ntdll.dll
CREATE_THREAD PID=4860 TID=5052
CREATE_THREAD PID=4860 TID=5068
CREATE_THREAD PID=4860 TID=5072
CREATE_THREAD PID=4860 TID=5088
CREATE_THREAD PID=4860 TID=4140
CREATE_THREAD PID=4860 TID=4160
CREATE_THREAD PID=4860 TID=4180
CREATE_THREAD PID=4860 TID=5924
CREATE_THREAD PID=4860 TID=5968
CREATE_THREAD PID=4860 TID=5980
CREATE_THREAD PID=4860 TID=5988
CREATE_THREAD PID=4860 TID=6036
CREATE_THREAD PID=4860 TID=6112
CREATE_THREAD PID=4860 TID=6128
CREATE_THREAD PID=4860 TID=5572
CREATE_THREAD PID=4860 TID=6088
CREATE_THREAD PID=4860 TID=6264
CREATE_THREAD PID=4860 TID=6296
CREATE_THREAD PID=4860 TID=4900
CREATE_THREAD PID=4860 TID=9096
CREATE_THREAD PID=4860 TID=3352
CREATE_THREAD PID=4860 TID=6696
CREATE_THREAD PID=4860 TID=9732
CREATE_THREAD PID=4860 TID=10392
CREATE_THREAD PID=4860 TID=10424
CREATE_THREAD PID=4860 TID=11256
CREATE_THREAD PID=4860 TID=10780
CREATE_THREAD PID=4860 TID=9396
CREATE_THREAD PID=4860 TID=2384
CREATE_THREAD PID=4860 TID=5416
CREATE_THREAD PID=4860 TID=10020
CREATE_THREAD PID=4860 TID=10004
CREATE_THREAD PID=4860 TID=9240
CREATE_THREAD PID=4860 TID=8736
CREATE_THREAD PID=4860 TID=4240
CREATE_THREAD PID=4860 TID=9284
CREATE_THREAD PID=4860 TID=2680
CREATE_THREAD PID=4860 TID=9336
CREATE_THREAD PID=4860 TID=7220
CREATE_THREAD PID=4860 TID=5224
CREATE_THREAD PID=4860 TID=1772
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000076B10000 kernel32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCE30000 KernelBase.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEE90000 advapi32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEF70000 msvcrt.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEE30000 sechost.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFED00000 rpcrt4.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE700000 gdi32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000076C30000 user32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEE80000 lpk.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE810000 usp10.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEA40000 shlwapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFD030000 shell32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE4F0000 ole32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFDDC0000 oleaut32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED360000 ExplorerFrame.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA940000 duser.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFAAB0000 dui70.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFF010000 imm32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE8E0000 msctf.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB230000 uxtheme.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB060000 powrprof.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEAC0000 setupapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB00000 cfgmgr32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCE10000 devobj.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA8E0000 dwmapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9FE0000 slc.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFAE10000 GdiPlus.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC860000 secur32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC8B0000 sspicli.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB290000 propsys.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC9F0000 winsta.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED950000 tiptsf.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBE10000 version.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC940000 cryptbase.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBA20000 comctl32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA130000 WindowsCodecs.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCAE0000 profapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC8E0000 apphelp.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE770000 clbcatq.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000068480000 seafile_shell_ext64.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCD50000 userenv.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000000006B600000 TortoiseOverlays.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000000006B620000 TortoiseGitStub.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000069750000 TortoiseGit.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED620000 libgit2_tgit.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED800000 zlib1_tgit.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF4BA0000 msvcr120.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE9F0000 ws2_32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFEE70000 nsi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCBA0000 crypt32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCAF0000 msasn1.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF5C00000 winhttp.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF5B80000 webio.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED120000 gitdll.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF4D30000 msvcp120.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC2E0000 cryptsp.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBFE0000 rsaenh.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED7E0000 crshhndl.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED7A0000 DropboxExt64.26.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED790000 IconCodecService.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCA30000 RpcRtRemote.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA850000 SndVolSSO.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA930000 hid.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFAD10000 MMDevAPI.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED530000 timedate.cpl
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFAA90000 atl.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED030000 actxprxy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFABB0000 ntmarta.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFECA0000 Wldap32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED750000 shdocvw.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED020000 linkinfo.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB3E0000 shacct.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB3C0000 samlib.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEECFD0000 msls31.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEECD20000 gameux.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA8A0000 xmllite.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF2860000 wer.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB520000 authui.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB410000 cryptui.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000076F00000 psapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEAFF0000 networkexplorer.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEC610000 ntshrui.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC7B0000 srvcli.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF3600000 cscapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCEA0000 urlmon.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB90000 api-ms-win-downlevel-ole32-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB50000 api-ms-win-downlevel-shlwapi-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB80000 api-ms-win-downlevel-advapi32-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB60000 api-ms-win-downlevel-user32-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB40000 api-ms-win-downlevel-version-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCB70000 api-ms-win-downlevel-normaliz-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000076EF0000 normaliz.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFDEA0000 iertutil.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFE290000 wininet.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF1190000 api-ms-win-downlevel-advapi32-l2-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEC600000 msiltcfg.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF4720000 msi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA6F0000 UIAnimation.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8BE0000 DpOFeedb.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8A50000 stobject.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEC860000 batmeter.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBD30000 wtsapi32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFCD10000 wintrust.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA040000 es.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7640000 prnfldr.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7F70000 winspool.drv
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8F60000 DpoSet.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA7A0000 AudioSes.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEC6F0000 DXP.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8A30000 Syncreg.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE69F0000 netshell.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF96D0000 IPHLPAPI.DLL
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF95A0000 winnsi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA780000 nlaapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8A20000 AltTab.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8020000 WPDShServiceObj.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF23D0000 PortableDeviceTypes.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF2540000 PortableDeviceApi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7360000 BTNCopy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000064380000 DragExt64.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB740000 netutils.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9100000 mssprxy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE6830000 pnidui.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7620000 QUTIL.DLL
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC4F0000 wevtapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9120000 dhcpcsvc.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8F40000 dhcpcsvc6.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBE00000 credssp.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF26A0000 npmproxy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEACA0000 cscui.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8A10000 cscdll.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEC6B0000 cscobj.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF6840000 wlanapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF84A0000 wlanutil.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE66F0000 WWanAPI.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7D20000 wwapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEEAC50000 QAGENT.DLL
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE6690000 srchadmin.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBC30000 bthprops.cpl
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE6230000 ActionCenter.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4E40000 SyncCenter.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4DC0000 imapi2.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4D60000 hgcpl.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4D20000 provsvc.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC950000 sxs.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE65D0000 BtMmHook.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7930000 oleacc.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4BD0000 FXSST.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE47A0000 FXSAPI.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000000006B760000 FXSRESM.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEED880000 msftedit.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4650000 zipfldr.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB720000 wkscli.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7610000 api-ms-win-downlevel-shlwapi-l2-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4510000 UIAutomationCore.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE5360000 ieproxy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE2070000 ieframe.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4640000 api-ms-win-downlevel-shell32-l1-1-0.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE3F10000 StructuredQuery.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFA9C0000 winmm.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF4CB0000 mpr.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE3DB0000 PhotoBase.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFB970000 devrtl.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4CB0000 mlang.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF1D80000 wscinterop.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF11A0000 wscapi.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEDDE70000 wscui.cpl
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEDDD30000 werconcpl.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF3680000 framedynos.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF1DF0000 wercplsupport.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF2630000 hcproviders.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE48A0000 twext.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7990000 nvapi64.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF5260000 netprofm.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4460000 VAN.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEDD200000 RASMM.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9490000 rasapi32.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9D30000 rasman.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF7310000 rtutils.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF9FF0000 dsrole.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF81B0000 msxml6.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE1B30000 wwanmm.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEDD130000 WlanMM.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF4D00000 wlanhlp.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8B60000 onex.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8B40000 eappprxy.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEF8AF0000 eappcfg.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFC430000 bcrypt.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEFBF20000 bcryptprimitives.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FEE4880000 thumbcache.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECDD50000 GROOVEEX.DLL
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000000006EC60000 msvcr90.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=00000000690F0000 msvcp90.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=0000000071290000 ATL90.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECBC60000 GrooveIntlResource.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECD930000 OFFICE.ODF
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECB9E0000 wpdshext.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECB9A0000 EhStorShell.dll
LOAD_DLL PID=4860 TID=4864 lpBaseOfDll=000007FECB970000 EhStorAPI.dll
CREATE_THREAD PID=4860 TID=9576
EXCEPTION PID=4860 TID=9576 ExceptionCode=0x80000003 dwFirstChance=1
EXIT_THREAD PID=4860 TID=9576 dwExitCode=0x0
EXCEPTION PID=4860 TID=5416 ExceptionCode=0xc0000374 dwFirstChance=0
```

**Comment by killing** [comment]
@liayn Dr.MinGW is supposed to print a stack trace of the crash. I don't know why it doesn't work.
Could you try the gdb way? Thanks.

**Comment by shoeper** [comment]
@Chilledheart I cannot install it properly due to errors: "Fehler: Konnte Datei 'mingw32.db' nicht von downloads.sourceforge.net übertragen : Connection timed out after 10656 milliseconds"
Means as much as not all data could get downloaded.

On typing in `gdb -p 4548`, I then just get command not found

**Comment by Chilledheart** [comment]
Hi Sven:
Sorry for the inconvenience. I am not sure, but you can set up DNS servers to "manual" such as 8.8.8.8 and retry again. I think it is due to a bug with pacman.

Thanks

**Comment by shoeper** [comment]
I gave it a try. Unfortunately the problem is that the connections times out. DNS works (no matter with or without Google DNS)

```
λ nslookup downloads.sourceforge.net
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Nicht autorisierende Antwort:
Name:    downloads.sourceforge.net
Address:  216.34.181.59
```

**Comment by shoeper** [comment]
btw. the new error is

```
Fehler: Konnte Datei 'msys.db' nicht von downloads.sourceforge.net übertragen : Connection timed out after 10563 milliseconds
```

Seems more likely to be a sourceforge server issue.

**Comment by shoeper** [comment]
At the moment the explorer crashes continously every ~minute.

**Comment by shoeper** [comment]
Could fix that by editing the three mirror lists in msys64\etc\pacman.d
There are two mirrors and I've put sourceforge at the second position and the other one at first position.

Unfortunately I still get this error: bash: gdb: command not found.

**Comment by liayn** [comment]
@shoeper Even though it seems a bit overkill, but maybe you can install Visual Studio. It should register as debugger as well.

**Comment by shoeper** [comment]
Thanks for the hint. Could be that I already have it with University licence.

**Comment by Chilledheart** [comment]
@shoeper yep. I think you can fix it by editing the pacman mirror list if it is due to the server failure. Anyway you still need to use `pacman` to install `mingw-w64-x86_64-gdb` package.

**Comment by killing** [comment]
@shoeper Visual Studio debugger doesn't recognize gcc debug symbols. So it won't help.

**Comment by liayn** [comment]
@killing Thanks for pointing that out, I totally missed that.

BTW: Exception code 0xC0000374 means STATUS_HEAP_CORRUPTION

**Comment by liayn** [comment]
Could it be that Dr. Mingw does not provide a stack trace due to missing pdb files?
https://github.com/jrfonseca/drmingw#where-should-i-put-the-pdb-files

**Comment by killing** [comment]
@liayn I don't think so. The extension is compiled with gcc, so the debug symbol is in GNU format. The symbols are already included in the binary. Only programs compiled with Visual Studio uses PDB files. I don't think Windows Explorer has any debug symbols included. But that shouldn't prevent us from print stack trace. The result should be, we should be able to see the function names and line numbers inside the extension.

**Comment by liayn** [comment]
If I read the output above correctly, explorer.exe is trying to create a thread, which fails and the exception is thrown by explorer.exe. This would explain the missing stacktrace. (I didn't install Windows Debug Symbols)

**Comment by mathieu-mp** [comment]
+1 on Win8.1
Explorer crashes every minute or so,  I disabled the extension as a workaround.

**Comment by killing** [comment]
@liayn @shoeper @mathieu-mp We currently have no clue what causes the crash. My guess is some very large folder and very long path may cause the problem. Do you have any?
And would anyone try to use gdb to catch the problem? Without a good stack trace it would be very hard to debug ;-)

**Comment by shoeper** [comment]
Unfortunately I wasn't able to get gdb to work.
Still get command not found although I've done all steps above.

**Comment by c-hri-s** [comment]
```
warning: *** CGDContextMenu::Initialize Num files selected: ***1
warning:

warning: *** CGDContextMenu::QueryContextMenu ***0
warning:

[New Thread 5716.0x29c8]
warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CSharePage::InitDlgInfo at line 57

warning: Leave function CSharePage::InitDlgInfo at line 62

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CPIMPage::InitDlgInfo at line 104

warning: Leave function CPIMPage::InitDlgInfo at line 109

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CAppShellPage::StopListen at line 145

warning: Leave function CAppShellPage::StopListen at line 148

[New Thread 5716.0x2c84]
[New Thread 5716.0x24ec]
[Thread 5716.0x2c84 exited with code 0]
[Thread 5716.0x24ec exited with code 0]
[New Thread 5716.0x1818]
[Thread 5716.0x1818 exited with code 0]
[Thread 5716.0x2fc0 exited with code 0]
[Thread 5716.0x2b64 exited with code 0]
[Thread 5716.0x2558 exited with code 0]
[Thread 5716.0x178c exited with code 0]
[Thread 5716.0x1d08 exited with code 0]
[New Thread 5716.0x2e6c]
[New Thread 5716.0x282c]
[Thread 5716.0x2e6c exited with code 0]
[Thread 5716.0x282c exited with code 0]
[New Thread 5716.0x2ddc]
[New Thread 5716.0x1960]
warning: QueryContextMenu interface called!
warning: Begin to create meun!

warning: *** CGDContextMenu::initialize ***
warning:

warning: *** CGDContextMenu::Initialize Num files selected: ***1
warning:

warning: *** CGDContextMenu::QueryContextMenu ***0
warning:

warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CSharePage::InitDlgInfo at line 57

warning: Leave function CSharePage::InitDlgInfo at line 62

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CPIMPage::InitDlgInfo at line 104

warning: Leave function CPIMPage::InitDlgInfo at line 109

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CAppShellPage::StopListen at line 145

warning: Leave function CAppShellPage::StopListen at line 148

[New Thread 5716.0x2ba4]
[New Thread 5716.0xbb4]
[Thread 5716.0x2ba4 exited with code 0]
[Thread 5716.0xbb4 exited with code 0]
[New Thread 5716.0x2ffc]
[Thread 5716.0x2ffc exited with code 0]
[Thread 5716.0x1960 exited with code 0]
[Thread 5716.0x2ddc exited with code 0]
[New Thread 5716.0x16f8]
[Thread 5716.0x16f8 exited with code 0]
[New Thread 5716.0x2740]
[New Thread 5716.0x1964]
[New Thread 5716.0x2ae8]
[Thread 5716.0x2740 exited with code 0]
[Thread 5716.0x1964 exited with code 0]
[Thread 5716.0x2ae8 exited with code 0]
warning: ***********Destruct CommApiHelper************
warning: *********CommApiHelper::UnInitCheck**************
warning: ***********Destruct CommApi2TrayHelper************
warning: **********CommApi2TrayHelper::UnInitCheck*************
[New Thread 5716.0x25d8]
[New Thread 5716.0x2f6c]
[New Thread 5716.0x9c0]
[New Thread 5716.0x2b30]
[New Thread 5716.0xcf0]
[New Thread 5716.0x4e4]
[New Thread 5716.0x2d44]
[New Thread 5716.0xc94]
[New Thread 5716.0x11ec]
[New Thread 5716.0x514]
[New Thread 5716.0x2944]
[New Thread 5716.0x2d58]
[New Thread 5716.0x2134]
[Thread 5716.0x25d8 exited with code 0]
[Thread 5716.0x2d44 exited with code 0]
[New Thread 5716.0x1ee0]
[New Thread 5716.0x2f4c]
[Thread 5716.0x1ee0 exited with code 0]
[New Thread 5716.0x1204]
[Thread 5716.0x1204 exited with code 0]
[Thread 5716.0x2134 exited with code 0]
[New Thread 5716.0x2db4]
[New Thread 5716.0x2198]
[New Thread 5716.0x2c58]
[New Thread 5716.0x1e5c]
[New Thread 5716.0x2ed8]
warning: ***********Create CommApi2Trayhelper************
warning: QueryContextMenu interface called!
warning: Begin to create meun!

warning: RegQueryValueEx returns a value of C:\Program Files (x86)\Google\Drive\googledrivesync.exe and buffer_length of 112
warning:

warning: *** CGDContextMenu::initialize ***
warning:

warning: *** CGDContextMenu::Initialize Num files selected: ***1
warning:

warning: *** CGDContextMenu::QueryContextMenu ***0
warning:

warning: *************Create CommApiHelper**********
warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CSharePage::InitDlgInfo at line 57

warning: Leave function CSharePage::InitDlgInfo at line 62

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CPIMPage::InitDlgInfo at line 104

warning: Leave function CPIMPage::InitDlgInfo at line 109

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CAppShellPage::StopListen at line 145

warning: Leave function CAppShellPage::StopListen at line 148

[New Thread 5716.0x28b4]
[Thread 5716.0x28b4 exited with code 0]
[Thread 5716.0x2ed8 exited with code 0]
[New Thread 5716.0x2340]
[Thread 5716.0x1e5c exited with code 0]
[Thread 5716.0x2db4 exited with code 0]
[Thread 5716.0x2340 exited with code 0]
[New Thread 5716.0x2f74]
[New Thread 5716.0x2e20]
[Thread 5716.0x2f74 exited with code 0]
[Thread 5716.0x2e20 exited with code 0]
warning: ***********Destruct CommApiHelper************
warning: *********CommApiHelper::UnInitCheck**************
warning: ***********Destruct CommApi2TrayHelper************
warning: **********CommApi2TrayHelper::UnInitCheck*************
[New Thread 5716.0xfe4]
[Thread 5716.0xfe4 exited with code 0]
[New Thread 5716.0x175c]
[Thread 5716.0x175c exited with code 0]
[New Thread 5716.0x249c]
[Thread 5716.0x29c8 exited with code 0]
[Thread 5716.0x249c exited with code 0]
[New Thread 5716.0x948]
[New Thread 5716.0x2f98]
[Thread 5716.0x948 exited with code 0]
[New Thread 5716.0x1450]
[New Thread 5716.0x970]
warning: ***********Create CommApi2Trayhelper************
warning: QueryContextMenu interface called!
warning: Begin to create meun!

warning: RegQueryValueEx returns a value of C:\Program Files (x86)\Google\Drive\googledrivesync.exe and buffer_length of 112
warning:

warning: *** CGDContextMenu::initialize ***
warning:

warning: *** CGDContextMenu::Initialize Num files selected: ***1
warning:

warning: *** CGDContextMenu::QueryContextMenu ***1
warning:

[New Thread 5716.0x2378]
warning: *************Create CommApiHelper**********
warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CSharePage::InitDlgInfo at line 57

warning: Leave function CSharePage::InitDlgInfo at line 62

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CPageBase::InitInstance at line 160

warning: Enter function CPIMPage::InitDlgInfo at line 104

warning: Leave function CPIMPage::InitDlgInfo at line 109

warning: Leave function CPageBase::InitInstance at line 168

warning: Enter function CAppShellPage::StopListen at line 145

warning: Leave function CAppShellPage::StopListen at line 148

[New Thread 5716.0x1234]
[Thread 5716.0x1234 exited with code 0]
[Thread 5716.0x970 exited with code 0]
[New Thread 5716.0xdd0]
[Thread 5716.0x1450 exited with code 0]
[Thread 5716.0x2f98 exited with code 0]
[Thread 5716.0xdd0 exited with code 0]
[New Thread 5716.0x27a8]
[New Thread 5716.0x271c]
[Thread 5716.0x27a8 exited with code 0]
[Thread 5716.0x271c exited with code 0]
[New Thread 5716.0x1a2c]
[New Thread 5716.0x2a54]
[Thread 5716.0x1a2c exited with code 0]
[New Thread 5716.0xfac]
[New Thread 5716.0x2248]
[Thread 5716.0x2a54 exited with code 0]
warning: ***********Destruct CommApiHelper************
warning: *********CommApiHelper::UnInitCheck**************
warning: ***********Destruct CommApi2TrayHelper************
warning: **********CommApi2TrayHelper::UnInitCheck*************
[Thread 5716.0xfac exited with code 0]
[New Thread 5716.0x1388]
[Thread 5716.0x2248 exited with code 0]
[New Thread 5716.0x1738]
[Thread 5716.0x2378 exited with code 0]
[Thread 5716.0x1388 exited with code 0]
[New Thread 5716.0x2ea8]
[New Thread 5716.0x237c]
[Thread 5716.0x1738 exited with code 0]
[New Thread 5716.0x171c]
[New Thread 5716.0x2e94]
[New Thread 5716.0x24e0]
[Thread 5716.0x24e0 exited with code 1]
[New Thread 5716.0x24ec]
[Thread 5716.0x2ea8 exited with code 0]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 5716.0x2944]
0x00000000772f10e2 in ntdll!RtlAnsiStringToUnicodeString ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00000000772f10e2 in ntdll!RtlAnsiStringToUnicodeString ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x000007fefebb10c8 in msvcrt!free () from C:\Windows\system32\msvcrt.dll
#2  0x000000006849fb1c in seafile::RepoInfo::~RepoInfo (this=0x24c1c0,
    __in_chrg=<optimized out>)
    at D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-4.2.6/extensions/commands.h:11
#3  0x00000000685087e5 in std::_Destroy<seafile::RepoInfo> (
    __pointer=0x24c1c0)
    at c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/stl_construct.h:95
#4  0x00000000684deda3 in std::_Destroy_aux<false>::__destroy<seafile::RepoInfo*> (__first=0x24c1c0, __last=0x24c320)
    at c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/stl_construct.h:105
#5  0x0000000068508870 in std::_Destroy<seafile::RepoInfo*> (
    __first=0x24c160, __last=0x24c320)
    at c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/stl_construct.h:128
#6  0x00000000685088a4 in std::_Destroy<seafile::RepoInfo*, seafile::RepoInfo>
    (__first=0x24c160, __last=0x24c320)
    at c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/stl_construct.h:155
#7  0x00000000684fe581 in std::vector<seafile::RepoInfo, std::allocator<seafile::RepoInfo> >::~vector (this=0xec9f0f0, __in_chrg=<optimized out>)
    at c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/stl_vector.h:403
#8  0x000000006848239c in ShellExt::pathInRepo (this=0x599850, path=...,
    path_in_repo=0xec9f2f0, repo=0xec9f2d0)
    at D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-4.2.6/extensions/shell-ext.cpp:120
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00000000772f10e2 in ntdll!RtlAnsiStringToUnicodeString ()
   from C:\Windows\SYSTEM32\ntdll.dll
```

**Comment by liayn** [comment]
I got a stracktrace by Dr.Mingw:

```
CREATE_THREAD PID=16824 TID=15536
EXCEPTION PID=16824 TID=15536 ExceptionCode=0x80000003 dwFirstChance=1
EXIT_THREAD PID=16824 TID=15536 dwExitCode=0x0
EXCEPTION PID=16824 TID=6036 ExceptionCode=0xc0000005 dwFirstChance=0
explorer.exe caused an Access Violation at location 00000000684D9B1B in module seafile_shell_ext64.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00000000684D9B1B 000000000862E300 0000000076B317B0 0000000080004005  seafile_shell_ext64.dll! ?? ??   [c:/bb/vista64-mingw32/mingw-x86-x86_64/build/build/gcc/obj/x86_64-w64-mingw32/libstdc++-v3/include/bits/basic_string.h @ 424]
000000006849F6CE 0000000000489510 00000000004894A0 0000000080004005  seafile_shell_ext64.dll! ?? ??   [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/guiddef.h @ 142]
0000000068503AEE 0000000000489510 00000000004894A0 0000000080004005  seafile_shell_ext64.dll!_Construct<seafile::RepoInfo, const seafile::RepoInfo&>  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
00000000684F9EA7 00000000004894A0 00000000004894E0 00000000004894F0  seafile_shell_ext64.dll!__uninit_copy<__gnu_cxx::__normal_iterator<const seafile::RepoInfo*, std::vector<seafile::RepoInfo> >, seafile::RepoInfo*>  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
0000000068505E4B 0000000000489480 00000000004894E0 00000000004894F0  seafile_shell_ext64.dll!uninitialized_copy<__gnu_cxx::__normal_iterator<const seafile::RepoInfo*, std::vector<seafile::RepoInfo> >, seafile::RepoInfo*>  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
0000000068506E5F 0000000000489480 00000000004894E0 00000000004894F0  seafile_shell_ext64.dll!__uninitialized_copy_a<__gnu_cxx::__normal_iterator<const seafile::RepoInfo*, std::vector<seafile::RepoInfo> >, seafile::RepoInfo*, seafile::RepoInfo>  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
00000000684FE159 000000000862EC80 0000000000000003 0000000000489480  seafile_shell_ext64.dll!_M_allocate_and_copy<__gnu_cxx::__normal_iterator<const seafile::RepoInfo*, std::vector<seafile::RepoInfo> > >  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
00000000684FE769 000000000862EC80 00000000004236A0 000000000862EC74  seafile_shell_ext64.dll!operator=  [c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/include/c++/4.7.0/bits/char_traits.h @ 257]
0000000068481EAD 0000000000219690 000000000862EC80 0000000000000000  seafile_shell_ext64.dll!getReposList  [D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-4.2.6/extensions/shell-ext.cpp @ 96]
0000000068482165 0000000000219690 000000000862EE90 000000000862EE80  seafile_shell_ext64.dll!pathInRepo  [D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-4.2.6/extensions/shell-ext.cpp @ 121]
0000000068484AC3 0000000000219690 000000000862F0D0 0000000000000011  seafile_shell_ext64.dll!IsMemberOf  [D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-4.2.6/extensions/icon-overlay.cpp @ 82]
000007FEFD076B1B 0000000080004005 000007FEFD0727B7 000000000862F070  SHELL32.dll!CFSIconOverlayManager::_GetFileOverlayInfo
000007FEFD190F50 FFFFFFFFF47E2860 0000000000000001 000007FEED4857F0  SHELL32.dll!CFSIconOverlayManager::GetFileOverlayInfo
000007FEFD071D13 000000000B81D7A0 00000000042A6AA0 0000B8D1F4E40FFE  SHELL32.dll!CFSFolder::_GetOverlayInfo
000007FEFD071C24 0000000000000000 00000000042A6AA0 000000000862F498  SHELL32.dll!CFSFolder::GetOverlayIndex
000007FEFD1871E0 000000007FFFFFFF 000007FFFFFD9000 00000000033C9F90  SHELL32.dll!CRegFolder::_GetOverlayInfo
000007FEFD0926A7 000000000F3BB860 0000000000000000 0000000000000000  SHELL32.dll!CRegFolder::GetOverlayIndex
000007FEED39B213 000000000F3BB860 000007FEFFFFFFFF 000000000862F528  EXPLORERFRAME.dll!CNscOverlayTask::_Extract
000007FEED39AFCF 00000000042A6AC8 00000000055EF934 0000000000000000  EXPLORERFRAME.dll!CNscOverlayTask::InternalResumeRT
000007FEED36BE50 8000000001000000 000000000862F520 FFFFFFFFFFFFFFFE  EXPLORERFRAME.dll!CRunnableTask::Run
000007FEFD0CF203 00000000033724E0 000000000FA15CC0 FFFFFFFFFFFFFFFE  SHELL32.dll!CShellTask::TT_Run
000007FEFD0CF143 00000000033724E0 00000000033724E0 0000000000000000  SHELL32.dll!CShellTaskThread::ThreadProc
000007FEFD0D2DF2 00000000033C9F90 0000000003372500 0000000000000000  SHELL32.dll!CShellTaskThread::s_ThreadProc
000007FEFEA53843 000000000EED34A0 000007FFFFFD9000 0000B8D1F4E4143D  SHLWAPI.dll!ExecuteWorkItemThreadProc
0000000076D50D5B 0000000000000000 0000000003372500 00000000003203B0  ntdll.dll!RtlpTpWorkCallback
0000000076D503D6 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!TppWorkerThread
0000000076B259CD 0000000000000000 0000000000000000 0000000000000000  kernel32.dll!BaseThreadInitThunk
0000000076D5B981 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

EXIT_THREAD PID=16824 TID=13428 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=18904 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=15296 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=18172 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=7196 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=18288 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=6528 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=3576 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=1528 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=4708 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=18328 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=17308 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=1576 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=17492 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=11232 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=14032 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=11476 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=3028 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=10532 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=16124 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=19176 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=17936 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=6864 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=14852 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=16500 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=19716 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=12660 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=9132 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=4188 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=7840 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=17276 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=12088 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=12672 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=10308 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=7572 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=18584 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=16840 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=20132 dwExitCode=0xc0000005
EXIT_THREAD PID=16824 TID=7932 dwExitCode=0xc0000005
EXIT_PROCESS PID=16824 TID=6036 dwExitCode=0xc0000005
```

**Comment by killing** [comment]
Hi all, thanks to your stack trace, we've fixed the bug. Here is a test package: https://bintray.com/artifact/download/seafile-org/seafile/seafile-4.2.7-en.msi

**Comment by liayn** [comment]
No crashes so far.

**Comment by shoeper** [comment]
Same here on my parents laptop using windows 7.

**Comment by mathieu-mp** [comment]
Same here, no crash
Well done!

**Comment by mathieu-mp** [comment]
OK, big crash today...

...plus some annoyance with "modified" badges that won't update.

2015-07-08 20:02 GMT+02:00 Sven <notifications@github.com>:

**Comment by killing** [comment]
@mathieu-mp Here is another fix. It may fix your new crash problem and the icon update problem.
https://bintray.com/artifact/download/seafile-org/seafile/seafile-4.2.8.msi

**Comment by liayn** [comment]
Since there haven't been any crash reports in the last week, I consider this fixed.

**Comment by lucasevabou14** [comment]
Hi, Suspected several explorer crash on 6.0.6.

Nom de l’application défaillante Explorer.EXE, version : 6.1.7601.23537, horodatage : 0x57c44efe
Nom du module défaillant : kernel32.dll, version : 6.1.7601.23677, horodatage : 0x589c9a26
Code d’exception : 0xc0000409
Décalage d’erreur : 0x0000000000021961
ID du processus défaillant : 0xf20
Heure de début de l’application défaillante : 0x01d2ced7b6f394b3
Chemin d’accès de l’application défaillante : C:\Windows\Explorer.EXE
Chemin d’accès du module défaillant: C:\Windows\system32\kernel32.dll
ID de rapport : be3da0ec-3afc-11e7-b741-54f856656209
