### ISSUE TITLE
Client closes connection on low bandwidth situations

### ISSUE THREAD

**Issue by tuxayo** [haiwen/seafile-client#776]
This is a follow up of [a discussion on the forum](https://forum.seafile-server.org/t/syncing-problems-on-low-bandwidth/3690/8).

The issue can also be trigger by reducing the upload limit.
The web server reports a connection closed by the client. 

It seems to be a low [timeout issue](https://forum.seafile-server.org/t/syncing-problems-on-low-bandwidth/3690/14)

cc @killing @shoeper @freeplant @mmrose @gileri

**Comment by freeplant** [comment]
Please try v5.0.6.

**Comment by gileri** [comment]
Can someone point to the relevant commits which fixes this ? I can't find them, apart from the mention in the 5.0.6 client changelog.

**Comment by killing** [comment]
It's fixed in https://github.com/haiwen/seafile/commit/21b4dd9a26bbcadf9fbb5873ca7aacfd9f21354c
We increase the timeout to 120 seconds.

**Comment by gileri** [comment]
Thank you !

**Comment by tuxayo** [comment]
I can still reproduce the errors with the client in v5.1.0.
By uploading 10MB files with random data and limiting the upload speed in the settings I get the following results:
30KB/s → ok
25KB/s → ok
20KB/s → ok
15KB/s → errors but it painfully manages to upload the file (in more than twice the time of the 20KiB test)
10KB/s → errors but it painfully manages to upload the file
05KB/s → errors but it painfully manages to upload the file

The errors are:
server logs: client prematurely closed connection
client logs: libcurl failed to PUT

Note that the client doesn't seems respect strictly the speed limit, it never displays a upload of less than 16KB/s.


I regret to not have performed such tests **before** upgrading the client. So we could have a comparison.

@gileri @mmrose Do you still have 5.0.5 client installed by any chance?

**Comment by shoeper** [comment]
I did have a similar experience before. So I don't think this behaviour 
happened due to changes in v5.1.


Am 10. April 2016 19:59:34 schrieb Victor <notifications@github.com>:

**Comment by tuxayo** [comment]
> So I don't think this behaviour happened due to changes in v5.1.

That was the initial bug before 5.0.6 so indeed it's not new.
And increasing the timeout in 5.0.6 hopefully mitigated it for most of the cases.
