### ISSUE TITLE
Can't unsync selected folders that have been synced a while ago

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-client#851]
They do not appear in the Library list, once they are not included in the "recent" list anymore.

(MacOS client 5.1.4, Seafile Server 6.0.6)

**Scenario:**

I did a selective sync of a folder. Now I want to sync that folder with another seafile.
The error message is, that the folder already is being synced (which is quite right).

I can't unsync the folder in the other seafile though, because it does not show up in any of the lists in the client, because it's not a library and not a private share and has not recently been changed.

It sort of falls through the raster.

Hope that makes sense,

Chris

**Comment by shoeper** [comment]
I can confirm this bug, did experience the same recently.

**Comment by kforner** [comment]
Similar problem here. 
To reproduce it : 
  -  selective sync a folder
  - explicitly logout (from the client)
  - login again --> the folder is no more listed in  the Synced Libraries

**Comment by freeplant** [comment]
This problem should have been fixed in the latest release.

**Comment by shoeper** [comment]
This has not been fixed. Synchronized subfolders are still not shown in the libraries list of the device.

**Comment by shoeper** [comment]
See also https://github.com/haiwen/seafile-client/issues/903

**Comment by freeplant** [comment]
```
To reproduce it :

selective sync a folder
explicitly logout (from the client)
login again --> the folder is no more listed in the Synced Libraries
```

This has been fixed.

For existing synced sub-folders, because the information is already lost, they will not be shown in the list.
